name: 'Asciidoctor Setup'
description: 'Install and set up asciidoctor quickly.'
author: 'reitzig'
inputs:
  version:
    description: |
        The version of asciidoctor to install.
        Example: 2.0.10
    required: false
    default: '~>2.0'
  options:
    description: |
        Any options every run of asciidoctor should use.
        Example: "-a experimental=true -d inline"
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'yellow'
